const P={"stats": [["AI / ML", "Focus"], ["Deep Learning", "Research"], ["Computer Vision", "Focus"], ["Smart Agriculture", "Application"]], "links": [["Google Scholar", "#"], ["SINTA", "#"], ["ORCID", "#"], ["GitHub", "https://github.com/miftahsholihinteknik-max"]], "skills": ["Artificial Intelligence", "Machine Learning", "Deep Learning", "Computer Vision", "Image Processing", "CNN", "LSTM", "Transfer Learning", "Python", "TensorFlow", "Keras"], "research": [["01", "Artificial Intelligence", "Sistem cerdas untuk klasifikasi, prediksi, diagnosis, dan pengambilan keputusan berbasis data."], ["02", "Computer Vision", "Deep learning untuk klasifikasi citra, deteksi objek, dan analisis visual."], ["03", "Smart Agriculture", "AI untuk pertanian presisi, diagnosis tanaman, prediksi lingkungan, dan monitoring."]], "education": [["—", "Program Magister / Doktor", "Tambahkan universitas dan tahun."], ["—", "Program Sarjana", "Tambahkan universitas dan tahun."]], "contact": [["Email", "Tambahkan email akademik", "#"], ["Institution", "Universitas Islam Lamongan", "#"], ["GitHub", "miftahsholihinteknik-max", "https://github.com/miftahsholihinteknik-max"]]};const PUB=[["2025", "Deep Learning for Plant Disease Classification", "Journal / Publisher", "https://doi.org/"], ["2025", "LSTM-Based Environmental Prediction", "Journal / Publisher", "https://doi.org/"], ["2024", "Explainable AI for Precision Agriculture", "Journal / Publisher", "https://doi.org/"]];const COURSES=[{"code": "IF4501", "name": "Machine Learning", "description": "Konsep, algoritma, implementasi, evaluasi, dan pengembangan model.", "meetings": 16}, {"code": "—", "name": "Artificial Intelligence", "description": "Konsep kecerdasan buatan dan sistem cerdas.", "meetings": 16}, {"code": "—", "name": "Pengolahan Citra Digital", "description": "Pengolahan citra dan implementasi computer vision.", "meetings": 16}, {"code": "—", "name": "Struktur Data", "description": "Struktur data, algoritma, dan kompleksitas.", "meetings": 16}];const RES=[{"course": "Machine Learning", "meeting": 1, "title": "Pengantar Machine Learning", "type": "PDF", "description": "Konsep dasar, paradigma, dan workflow machine learning.", "url": "materials/machine-learning/pertemuan-01/README.txt"}, {"course": "Machine Learning", "meeting": 2, "title": "Data Preprocessing", "type": "PDF", "description": "Data cleaning, transformation, encoding, dan scaling.", "url": "materials/machine-learning/pertemuan-02/README.txt"}, {"course": "Machine Learning", "meeting": 3, "title": "Regression", "type": "PDF", "description": "Konsep regresi dan evaluasi model.", "url": "materials/machine-learning/pertemuan-03/README.txt"}, {"course": "Machine Learning", "meeting": 4, "title": "Classification", "type": "PDF", "description": "Konsep klasifikasi dan evaluasi model.", "url": "materials/machine-learning/pertemuan-04/README.txt"}];
async function get(f,d){try{let r=await fetch(f);if(!r.ok)throw 0;return await r.json()}catch(e){return d}}
const e=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function init(){const[p,pub,c,res]=await Promise.all([get("data/profile.json",P),get("data/publications.json",PUB),get("data/courses.json",COURSES),get("data/resources.json",RES)]);
stats.innerHTML=p.stats.map(x=>`<div class="number"><strong>${e(x[0])}</strong><span>${e(x[1])}</span></div>`).join("");
links.innerHTML=p.links.map(x=>`<a href="${e(x[1])}" target="_blank">${e(x[0])}</a>`).join("");skills.innerHTML=p.skills.map(x=>`<span class="skill">${e(x)}</span>`).join("");
researchGrid.innerHTML=p.research.map(x=>`<article class="research"><span class="index">${e(x[0])}</span><h3>${e(x[1])}</h3><p>${e(x[2])}</p></article>`).join("");
education.innerHTML=p.education.map(x=>`<article class="edu"><div class="year">${e(x[0])}</div><h3>${e(x[1])}</h3><p>${e(x[2])}</p></article>`).join("");
contactData.innerHTML=p.contact.map(x=>`<div class="contact-item"><label>${e(x[0])}</label><a href="${e(x[2])}" target="_blank">${e(x[1])}</a></div>`).join("");
let years=[...new Set(pub.map(x=>String(x[0])))].sort((a,b)=>b-a);pubFilters.innerHTML=['All',...years].map((x,i)=>`<button class="filter ${i?'':'active'}" data-f="${x}">${x}</button>`).join("");
pubs.innerHTML=pub.map(x=>`<article class="publication" data-y="${e(x[0])}"><div class="year">${e(x[0])}</div><div><h3>${e(x[1])}</h3><div class="meta">${e(x[2])}</div></div><a href="${e(x[3])}" target="_blank">DOI ↗</a></article>`).join("");
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".publication").forEach(x=>x.style.display=b.dataset.f==="All"||x.dataset.f===x.dataset.y?"grid":"none")});courses.innerHTML=c.map(x=>`<article class="course"><div class="code">${e(x.code)} · ${x.meetings} MEETINGS</div><h3>${e(x.name)}</h3><p>${e(x.description)}</p></article>`).join("");
function rr(q=""){resourcesGrid.innerHTML=res.filter(x=>(x.title+" "+x.course+" "+x.description).toLowerCase().includes(q.toLowerCase())).map(x=>`<article class="resource"><div class="type">${e(x.type)} · PERTEMUAN ${e(x.meeting)}</div><h3>${e(x.title)}</h3><p>${e(x.course)} — ${e(x.description)}</p><a href="${e(x.url)}" target="_blank">Open resource ↗</a></article>`).join("")}rr();search.oninput=()=>rr(search.value)}document.getElementById("year").textContent=new Date().getFullYear();menu.onclick=()=>navlinks.classList.toggle("open");theme.onclick=()=>{document.body.classList.toggle("darkmode");localStorage.dark=document.body.classList.contains("darkmode")};if(localStorage.dark==="true")document.body.classList.add("darkmode");init();