const fallback={stats:[["AI / ML","Focus"],["Deep Learning","Research"],["Computer Vision","Focus"],["Smart Agriculture","Application"]],links:[["Google Scholar","#"],["SINTA","#"],["ORCID","#"],["GitHub","https://github.com/miftahsholihinteknik-max"]],skills:["Artificial Intelligence","Machine Learning","Deep Learning","Computer Vision","Image Processing","CNN","LSTM","Transfer Learning","Python","TensorFlow","Keras"],research:[["01","Artificial Intelligence","Sistem cerdas untuk klasifikasi, prediksi, diagnosis, dan pengambilan keputusan berbasis data."],["02","Computer Vision","Deep learning untuk klasifikasi citra, deteksi objek, dan analisis visual."],["03","Smart Agriculture","AI untuk pertanian presisi, diagnosis tanaman, prediksi lingkungan, dan monitoring."]],publications:[["2025","Deep Learning for Plant Disease Classification","Journal / Publisher","https://doi.org/"],["2025","LSTM-Based Environmental Prediction","Journal / Publisher","https://doi.org/"],["2024","Explainable AI for Precision Agriculture","Journal / Publisher","https://doi.org/"]],courses:[["Machine Learning","Konsep, algoritma, implementasi, evaluasi, dan pengembangan model."],["Artificial Intelligence","Konsep kecerdasan buatan dan sistem cerdas."],["Pengolahan Citra Digital","Pengolahan citra dan implementasi computer vision."],["Struktur Data","Struktur data, algoritma, dan kompleksitas."]],education:[["—","Program Magister / Doktor","Tambahkan universitas dan tahun."],["—","Program Sarjana","Tambahkan universitas dan tahun."]],contact:[["Email","Tambahkan email akademik","#"],["Institution","Universitas Islam Lamongan","#"],["GitHub","miftahsholihinteknik-max","https://github.com/miftahsholihinteknik-max"]]};

async function data(){try{const r=await fetch("data/profile.json");if(!r.ok)throw 0;return await r.json()}catch(e){return fallback}}
function render(d){
document.getElementById("stats").innerHTML=d.stats.map(x=>`<div class="number"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join("");
document.getElementById("links").innerHTML=d.links.map(x=>`<a href="${x[1]}" target="_blank" rel="noopener">${x[0]}</a>`).join("");
document.getElementById("skills").innerHTML=d.skills.map(x=>`<span class="skill">${x}</span>`).join("");
document.getElementById("researchGrid").innerHTML=d.research.map(x=>`<article class="research"><span class="index">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("");
const pubs=document.getElementById("pubs");pubs.innerHTML=d.publications.map(x=>`<article class="publication" data-year="${x[0]}"><div class="year">${x[0]}</div><div><h3>${x[1]}</h3><div class="meta">${x[2]}</div></div><a href="${x[3]}" target="_blank" rel="noopener">DOI ↗</a></article>`).join("");
document.getElementById("courses").innerHTML=d.courses.map(x=>`<article class="course"><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join("");
document.getElementById("education").innerHTML=d.education.map(x=>`<article class="edu"><div class="year">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("");
document.getElementById("contactData").innerHTML=d.contact.map(x=>`<div class="contact-item"><label>${x[0]}</label><a href="${x[2]}" target="_blank" rel="noopener">${x[1]}</a></div>`).join("")}
document.getElementById("year").textContent=new Date().getFullYear();
document.getElementById("menu").onclick=()=>document.getElementById("navlinks").classList.toggle("open");
document.querySelectorAll(".navlinks a").forEach(a=>a.onclick=()=>document.getElementById("navlinks").classList.remove("open"));
document.querySelectorAll(".filter").forEach(btn=>btn.onclick=()=>{document.querySelectorAll(".filter").forEach(b=>b.classList.remove("active"));btn.classList.add("active");const f=btn.dataset.filter;document.querySelectorAll(".publication").forEach(p=>p.style.display=f==="all"||p.dataset.year===f?"grid":"none")});
data().then(render);